# python_basic2_writer.py

lines = [
    "1. Variables and Data Types",
    "x = 10        # Integer",
    "y = 3.14      # Float",
    "name = 'Shawon'  # String",
    "is_active = True # Boolean",
    "",
    "2. Basic Operators",
    "sum = x + y     # Addition",
    "diff = x - y    # Subtraction",
    "prod = x * y    # Multiplication",
    "quot = x / y    # Division",
    "",
    "3. Conditional Statements",
    "if x > y:",
    "    print('x is greater')",
    "else:",
    "    print('y is greater or equal')",
    "",
    "4. Loops",
    "for i in range(5):",
