# python_basic2_writer.py

lines = [
    "1. Variables and Data Types",
    "x = 10        # Integer",
    "y = 3.14      # Float",
    "name = 'Shawon'  # String",
    "is_active = True # Boolean",
    "",
    "2. Basic Operators",
    "sum = x + y     # Addition",
    "diff = x - y    # Subtraction",
    "prod = x * y    # Multiplication",
    "quot = x / y    # Division",
    "",
    "3. Conditional Statements",
    "if x > y:",
    "    print('x is greater')",
    "else:",
    "    print('y is greater or equal')",
    "",
    "4. Loops",
    "for i in range(5):",
    "    print(i)",
    "",
    "i = 0",
    "while i < 5:",
    "    print(i)",
    "    i += 1",
    "",
    "5. Functions",
    "def greet(name):",
    "    return f'Hello, {name}!'",
    "print(greet('Shawon'))",
    "",
    "6. Lists",
    "fruits = ['apple', 'banana', 'cherry']",
    "fruits.append('orange')",
    "print(fruits)",
    "",
    "7. Dictionaries",
    "person = {'name': 'Shawon', 'age': 22}",
    "print(person['name'])",
    "",
    "8. Classes and Objects",
    "class Person:",
    "    def __init__(self, name):",
    "        self.name = name",
    "    def speak(self):",
    "        print(f'My name is {self.name}')",
    "",
